//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace simProcess
{
	public class ConstantDouble : DoubleRandomProcess, DoubleProvider
	{
		double value = 1.0;

		public ConstantDouble (double val)
		{
			value = val;
		}

		double DoubleProvider.provideValue() 
		{
			return value;
		}
		
		double DoubleRandomProcess.nextValue() 
		{
			return value;
		}
		
		void DoubleRandomProcess.initialize(double initialValue, double[] parameters) 
		{
			value = initialValue;
		}
	}
}

